os:
  - osx
language: cpp
compiler:
    - gcc
    - clang
before_script:
    - brew update
    - brew install jsoncpp
    - brew install curl
    - mkdir build
    - cd build
    - cmake ..
script: make